name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install system dependencies
        run: sudo apt-get install musl-tools

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Build
        run: cargo build --release --all-features --target x86_64-unknown-linux-musl

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: crunchy-cli_linux
          path: ./target/x86_64-unknown-linux-musl/release/crunchy-cli
          if-no-files-found: error

      - name: Upload manpages artifact
        uses: actions/upload-artifact@v3
        with:
          name: manpages
          path: ./target/x86_64-unknown-linux-musl/release/manpages
          if-no-files-found: error

      - name: Upload completions artifact
        uses: actions/upload-artifact@v3
        with:
          name: completions
          path: ./target/x86_64-unknown-linux-musl/release/completions
          if-no-files-found: error

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-apple-darwin

      - name: Build
        run: cargo build --release --all-features --target x86_64-apple-darwin

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: crunchy-cli_darwin
          path: ./target/x86_64-apple-darwin/release/crunchy-cli
          if-no-files-found: error

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install system dependencies
        uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-rust base-devel

      - name: Build
        shell: msys2 {0}
        run: cargo build --release --all-features --target x86_64-pc-windows-gnu

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: crunchy-cli_windows
          path: ./target/x86_64-pc-windows-gnu/release/crunchy-cli.exe
          if-no-files-found: error
