[package]
name = "crunchy-cli-core"
authors = ["Crunchy Labs Maintainers"]
version = "3.0.1"
edition = "2021"
license = "MIT"

[features]
openssl = ["reqwest/native-tls-alpn"]
openssl-static = ["reqwest/native-tls-alpn", "reqwest/native-tls-vendored"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.3", features = ["derive", "string"] }
chrono = "0.4"
crunchyroll-rs = { version = "0.6.1", features = ["dash-stream"] }
ctrlc = "3.4"
dialoguer = { version = "0.10", default-features = false }
dirs = "5.0"
derive_setters = "0.1"
fs2 = "0.4"
indicatif = "0.17"
lazy_static = "1.4"
log = { version = "0.4", features = ["std"] }
num_cpus = "1.16"
regex = "1.9"
reqwest = { version = "0.11", default-features = false, features = ["socks"] }
sanitize-filename = "0.5"
serde = "1.0"
serde_json = "1.0"
serde_plain = "1.0"
shlex = "1.1"
tempfile = "3.7"
tokio = { version = "1.31", features = ["macros", "rt-multi-thread", "time"] }
sys-locale = "0.3"

[build-dependencies]
chrono = "0.4"

[patch.crates-io]
# fork of the `native-tls` crate which uses openssl as backend on every platform. this is done as `reqwest` only supports
# `rustls` and `native-tls` as tls backend
native-tls = { git = "https://github.com/crunchy-labs/rust-not-so-native-tls.git", rev = "570100d" }
