[package]
name = "crunchy-cli-core"
authors = ["Crunchy Labs Maintainers"]
version = "3.0.0-dev.1"
edition = "2021"

[features]
# Embed a static curl library into the binary instead of just linking it.
static-curl = ["crunchyroll-rs/static-curl"]
# Embed a static openssl library into the binary instead of just linking it. If you want to compile this project against
# musl and have openssl issues, this might solve these issues.
# Has no effect on Windows, the library is always statically linked there.
static-ssl = ["crunchyroll-rs/static-ssl"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "4.0", features = ["derive", "string"] }
chrono = "0.4"
crunchyroll-rs = { git = "https://github.com/crunchy-labs/crunchyroll-rs", default-features = false, features = ["stream", "parse"] }
ctrlc = "3.2"
dirs = "4.0"
isahc = { git = "https://github.com/sagebind/isahc", rev = "34f158ef" }
log = { version = "0.4", features = ["std"] }
num_cpus = "1.13"
regex = "1.6"
signal-hook = "0.3"
tempfile = "3.3"
terminal_size = "0.2"
tokio = { version = "1.21", features = ["macros", "rt-multi-thread", "time"] }
sys-locale = "0.2"

[build-dependencies]
chrono = "0.4"
